In [5]:
import os
import re
import csv

base_dir = "/project_cephfs/3022017.06/UKB/freesurfer/1875529/scripts/recon-all.log"
subject = "1875529"
output_csv = "euler_numbers.csv"

pattern = re.compile(r"orig\.nofix lheno =\s*([\-0-9]+), rheno =\s*([\-0-9]+)")

rows = []


#recon_all_path = os.path.join(base_dir, subject, "scripts", "recon-all.log")
recon_all_path = base_dir

if not os.path.isfile(recon_all_path):
    print(f"Missing log for {subject}")


lheno, rheno = None, None

with open(recon_all_path, "r") as f:
    for line in f:
        match = pattern.search(line)
        if match:
            lheno, rheno = match.groups()
            break

rows.append([subject, lheno, rheno])

print(rows)
# with open(output_csv, "w", newline="") as f:
#     writer = csv.writer(f)
#     writer.writerow(["subjectID", "lheno", "rheno"])
#     writer.writerows(rows)

[['1875529', '-24', '-34']]

In [6]:
import os
import re
import csv

base_dir = "/project_cephfs/3022017.06/UKB/freesurfer/"
output_csv = "euler_numbers.csv"

pattern = re.compile(r"orig\.nofix lheno =\s*([\-0-9]+), rheno =\s*([\-0-9]+)")

rows = []

for subject in os.listdir(base_dir):
    if not subject.isdigit():
        continue
    
    recon_all_path = os.path.join(base_dir, subject, "scripts", "recon-all.log")
    
    if not os.path.isfile(recon_all_path):
        print(f"Missing log for {subject}")
        continue
    
    lh_euler, rh_euler = None, None

    with open(recon_all_path, "r") as f:
        for line in f:
            match = pattern.search(line)
            if match:
                lh_euler, rh_euler = match.groups()
                break
    
    rows.append([subject, lh_euler, rh_euler])


with open(output_csv, "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(["SubjectID", "lh_euler", "rh_euler"])
    writer.writerows(rows)

In [26]:
import pandas as pd
import numpy as np

#euler data
df1 = pd.read_csv("/home/preclineu/quirom/Desktop/internship/Normative-Models-and-VAE/logs/csv_files/euler_numbers.csv")
df1

#data with correct site
df2 = pd.read_csv("/home/preclineu/quirom/Desktop/internship/Normative-Models-and-VAE/logs/final_data/Final_data_corrected_site.csv")

df_extra = df2[["SubjectID", "Site"]]


df3 = df1.merge(df_extra, on="SubjectID", how="right")

df3 = df3[df3["Site"] > 0]
df3 = df3.astype({"SubjectID": int, "lh_euler": int, "rh_euler": int, "Site": int})

df3["avg_euler"] = df3[["lh_euler", "rh_euler"]].mean(axis=1)
site_medians = df3.groupby("Site")["avg_euler"].median()
df3["Site_median"] = df3["Site"].map(site_medians)

df3["avg_euler_centered"] = df3["avg_euler"] - df3["Site_median"]

df3["avg_euler_centered_neg"] = -1 * df3["avg_euler_centered"]
df3["avg_euler_centered_neg_sqrt"] = np.sqrt(np.abs(df3["avg_euler_centered_neg"]))
good_subj_df = df3[df3["avg_euler_centered_neg_sqrt"] < 10]
bad_subj_df = df3[df3["avg_euler_centered_neg_sqrt"] > 10]

,SubjectID,lh_euler,rh_euler,Site,avg_euler,Site_median,avg_euler_centered,avg_euler_centered_neg,avg_euler_centered_neg_sqrt
40,3601900,-150,-136,11027,-143.0,-33.0,-110.0,110.0,10.488088
77,5620907,-140,-230,11025,-185.0,-31.0,-154.0,154.0,12.409674
451,4115393,-122,-162,11025,-142.0,-31.0,-111.0,111.0,10.535654
572,4614318,-146,-146,11025,-146.0,-31.0,-115.0,115.0,10.723805
801,5204817,-196,-230,11027,-213.0,-33.0,-180.0,180.0,13.416408
...,...,...,...,...,...,...,...,...,...
33409,5043120,-164,-176,11026,-170.0,-32.0,-138.0,138.0,11.747340
33494,3269123,-160,-118,11027,-139.0,-33.0,-106.0,106.0,10.295630
33744,5628573,-114,-158,11025,-136.0,-31.0,-105.0,105.0,10.246951
33840,5413291,-140,-146,11027,-143.0,-33.0,-110.0,110.0,10.488088
33929,1867149,-186,-196,11025,-191.0,-31.0,-160.0,160.0,12.649111

In [27]:
bad_subj_df.head(60)

,SubjectID,lh_euler,rh_euler,Site,avg_euler,Site_median,avg_euler_centered,avg_euler_centered_neg,avg_euler_centered_neg_sqrt
40,3601900,-150,-136,11027,-143.0,-33.0,-110.0,110.0,10.488088
77,5620907,-140,-230,11025,-185.0,-31.0,-154.0,154.0,12.409674
451,4115393,-122,-162,11025,-142.0,-31.0,-111.0,111.0,10.535654
572,4614318,-146,-146,11025,-146.0,-31.0,-115.0,115.0,10.723805
801,5204817,-196,-230,11027,-213.0,-33.0,-180.0,180.0,13.416408
936,4280688,-148,-238,11025,-193.0,-31.0,-162.0,162.0,12.727922
1007,5819650,-156,-174,11027,-165.0,-33.0,-132.0,132.0,11.489125
1011,4743877,-182,-160,11026,-171.0,-32.0,-139.0,139.0,11.789826
1097,2472743,-284,-272,11026,-278.0,-32.0,-246.0,246.0,15.684387
1169,1253728,-146,-128,11026,-137.0,-32.0,-105.0,105.0,10.246951
1185,2297218,-160,-150,11025,-155.0,-31.0,-124.0,124.0,11.135529
1271,1626510,-164,-116,11025,-140.0,-31.0,-109.0,109.0,10.440307
1458,1451614,-166,-124,11025,-145.0,-31.0,-114.0,114.0,10.677078
1469,1841200,-158,-136,11026,-147.0,-32.0,-115.0,115.0,10.723805
1474,3990941,-164,-180,11027,-172.0,-33.0,-139.0,139.0,11.789826
1537,2744505,-144,-128,11027,-136.0,-33.0,-103.0,103.0,10.148892
1549,4714453,-130,-172,11027,-151.0,-33.0,-118.0,118.0,10.862780
1664,3994938,-172,-158,11025,-165.0,-31.0,-134.0,134.0,11.575837
1717,5125670,-170,-128,11027,-149.0,-33.0,-116.0,116.0,10.770330
1833,1043197,-150,-164,11025,-157.0,-31.0,-126.0,126.0,11.224972
1919,1157106,-140,-140,11027,-140.0,-33.0,-107.0,107.0,10.344080
2007,1598267,-168,-140,11026,-154.0,-32.0,-122.0,122.0,11.045361
2089,2784980,-138,-152,11026,-145.0,-32.0,-113.0,113.0,10.630146
2149,5682634,-304,-242,11025,-273.0,-31.0,-242.0,242.0,15.556349
2566,1226318,-170,-158,11025,-164.0,-31.0,-133.0,133.0,11.532563
2580,2005937,-232,-232,11025,-232.0,-31.0,-201.0,201.0,14.177447
2813,5395079,-146,-128,11025,-137.0,-31.0,-106.0,106.0,10.295630
2816,2646076,-140,-128,11025,-134.0,-31.0,-103.0,103.0,10.148892
2857,1817634,-160,-128,11026,-144.0,-32.0,-112.0,112.0,10.583005
2869,5438364,-166,-136,11025,-151.0,-31.0,-120.0,120.0,10.954451
2935,2006661,-116,-158,11025,-137.0,-31.0,-106.0,106.0,10.295630
2983,2923876,-136,-134,11027,-135.0,-33.0,-102.0,102.0,10.099505
3055,3203846,-252,-90,11025,-171.0,-31.0,-140.0,140.0,11.832160
3056,2916787,-134,-138,11026,-136.0,-32.0,-104.0,104.0,10.198039
3103,1972575,-148,-120,11025,-134.0,-31.0,-103.0,103.0,10.148892
3129,1060911,-160,-154,11025,-157.0,-31.0,-126.0,126.0,11.224972
3154,2682627,-156,-112,11027,-134.0,-33.0,-101.0,101.0,10.049876
3184,3860995,-198,-134,11025,-166.0,-31.0,-135.0,135.0,11.618950
3245,5094453,-216,-162,11027,-189.0,-33.0,-156.0,156.0,12.489996
3460,4746162,-188,-154,11025,-171.0,-31.0,-140.0,140.0,11.832160
3527,3819385,-180,-118,11025,-149.0,-31.0,-118.0,118.0,10.862780
3534,2844344,-174,-156,11025,-165.0,-31.0,-134.0,134.0,11.575837
3774,3870686,-174,-128,11025,-151.0,-31.0,-120.0,120.0,10.954451
3914,4852805,-134,-140,11025,-137.0,-31.0,-106.0,106.0,10.295630
3983,1799769,-348,-236,11025,-292.0,-31.0,-261.0,261.0,16.155494
4146,1720717,-148,-144,11025,-146.0,-31.0,-115.0,115.0,10.723805
4168,1321651,-132,-144,11025,-138.0,-31.0,-107.0,107.0,10.344080
4264,3344702,-224,-326,11025,-275.0,-31.0,-244.0,244.0,15.620499
4351,4256513,-164,-144,11027,-154.0,-33.0,-121.0,121.0,11.000000
4501,1915246,-160,-136,11025,-148.0,-31.0,-117.0,117.0,10.816654
4594,3679365,-140,-160,11025,-150.0,-31.0,-119.0,119.0,10.908712
4765,2168452,-216,-204,11025,-210.0,-31.0,-179.0,179.0,13.379088
5234,5745862,-146,-134,11027,-140.0,-33.0,-107.0,107.0,10.344080
5349,5122057,-274,-286,11025,-280.0,-31.0,-249.0,249.0,15.779734
5437,2755761,-212,-154,11027,-183.0,-33.0,-150.0,150.0,12.247449
5487,4505125,-170,-120,11025,-145.0,-31.0,-114.0,114.0,10.677078
5503,2023962,-182,-140,11027,-161.0,-33.0,-128.0,128.0,11.313708
5578,3791778,-236,-130,11027,-183.0,-33.0,-150.0,150.0,12.247449
5595,2067356,-160,-124,11025,-142.0,-31.0,-111.0,111.0,10.535654
5731,5604546,-238,-184,11025,-211.0,-31.0,-180.0,180.0,13.416408

In [18]:
bad_subj_df

array([11025, 11026, 11027, 11028])

In [29]:
df = pd.read_csv("/home/preclineu/quirom/Desktop/internship/Normative-Models-and-VAE/logs/final_data/euler_nr_correct_site_data.csv")
df.head(80)

,Unnamed: 0,SubjectID,lh_euler,rh_euler,Site,avg_euler,Site_median,avg_euler_centered,avg_euler_centered_neg,avg_euler_centered_neg_sqrt
0,0,1533138,-70,-62,11025,-66.0,-31.0,-35.0,35.0,5.916080
1,1,1875529,-24,-34,11025,-29.0,-31.0,2.0,-2.0,1.414214
2,2,4758824,-18,-30,11025,-24.0,-31.0,7.0,-7.0,2.645751
3,3,5304207,-22,-28,11025,-25.0,-31.0,6.0,-6.0,2.449490
4,4,2747983,-20,-16,11025,-18.0,-31.0,13.0,-13.0,3.605551
...,...,...,...,...,...,...,...,...,...,...
75,76,2769684,-48,-26,11027,-37.0,-33.0,-4.0,4.0,2.000000
76,78,1228421,-30,-16,11025,-23.0,-31.0,8.0,-8.0,2.828427
77,79,4799061,-98,-128,11027,-113.0,-33.0,-80.0,80.0,8.944272
78,80,5671956,-40,-34,11025,-37.0,-31.0,-6.0,6.0,2.449490
79,81,4210331,-34,-32,11027,-33.0,-33.0,0.0,-0.0,0.000000