In [2]:
import pandas as pd 
import numpy as np
import os 
import glob
import re
pd.set_option('display.max_columns', 500)

In [3]:
df_orig = pd.read_csv("/home/preclineu/quirom/Desktop/internship/Normative-Models-and-VAE/logs/final_data/Final_data.csv")
df_orig = df_orig.iloc[:,2:]

In [8]:
#aseg code to extract the columns of dataframe [already used and extracted]
root_dir = "/project_cephfs/3022017.06/UKB/freesurfer/"
all_subject_dirs = [
    d for d in os.listdir(root_dir)
    if os.path.isdir(os.path.join(root_dir, d)) and re.match(r"^[A-Za-z0-9_\-]+$", d)
]

all_data = []

for subj in all_subject_dirs:
    subj_dir = os.path.join(root_dir, subj)
    aseg_path = os.path.join(subj_dir, "stats", "aseg.stats")

    if os.path.exists(aseg_path):        
        aseg_data = pd.read_csv(aseg_path, sep=r"\s+", comment="#", header=None)
        aseg_data = aseg_data.drop(aseg_data.columns[:2], axis=1)

        aseg_data.columns = [
            "NVoxels", "Volume_mm3", "StructName",
            "normMean", "normStdDev", "normMin", "normMax", "normRange"
        ]

        pivoted_data = aseg_data.pivot_table(
            index=None,
            columns="StructName",
            values= ["Volume_mm3"] 
        )

        pivoted_data["SubjectID"] = subj
        pivoted_data = pivoted_data.set_index("SubjectID")

        all_data.append(pivoted_data)

final_df = pd.concat(all_data, axis=0)

print("\nFinal combined DataFrame:")
print(final_df.head())

#final_df.to_csv("correct_aseg_stats.csv")

Final combined DataFrame:
StructName  3rd-Ventricle  4th-Ventricle  5th-Ventricle  Brain-Stem  \
SubjectID
1533138            1042.8         1818.5            0.0     19411.7
1875529            3248.4         2777.2            0.0     22865.0
4758824            1459.8         1194.8            0.0     19145.9
5304207             968.3         1442.7            0.0     21161.8
2747983             860.3         1447.2            0.0     21304.0

StructName  CC_Anterior  CC_Central  CC_Mid_Anterior  CC_Mid_Posterior  \
SubjectID
1533138           843.2       440.4            454.1             588.9
1875529           739.7       407.3            397.8             432.5
4758824          1050.7       478.7            450.6             574.6
5304207           910.5       718.3            660.4             652.7
2747983           882.6       559.7            624.6             612.5

StructName  CC_Posterior     CSF  ...  Right-Thalamus-Proper  Right-VentralDC  \
SubjectID                         ...
1533138            942.0   849.3  ...                 6420.0           3397.3
1875529            869.5   965.3  ...                 6855.6           4324.8
4758824           1099.9  1013.6  ...                 6274.4           3645.9
5304207           1142.6   821.1  ...                 6374.3           3564.4
2747983            923.9   932.2  ...                 6893.6           3838.9

StructName  Right-WM-hypointensities  Right-choroid-plexus  \
SubjectID
1533138                          0.0                 405.8
1875529                          0.0                 909.3
4758824                          0.0                 500.8
5304207                          0.0                 303.4
2747983                          0.0                 540.0

StructName  Right-non-WM-hypointensities  Right-vessel  WM-hypointensities  \
SubjectID
1533138                              0.0          23.2              2197.7
1875529                              0.0          29.9              2288.2
4758824                              0.0          71.5              1448.0
5304207                              0.0          48.0               858.6
2747983                              0.0          68.4               694.2

StructName  non-WM-hypointensities  Left-Thalamus  Right-Thalamus
SubjectID
1533138                        0.0            NaN             NaN
1875529                        0.0            NaN             NaN
4758824                        0.0            NaN             NaN
5304207                        0.0            NaN             NaN
2747983                        0.0            NaN             NaN

[5 rows x 47 columns]

In [31]:
df_orig = pd.read_csv("/home/preclineu/quirom/Desktop/internship/Normative-Models-and-VAE/logs/final_data/Final_data.csv")
df_new = pd.read_csv("/home/preclineu/quirom/Desktop/internship/Normative-Models-and-VAE/logs/data_prep/volume_mm3_aseg_stats.csv")
df_orig = df_orig.iloc[:,2:]
df_orig["SubjectID_new"] = df_orig["SubjectID"]
df_orig = df_orig.iloc[:,45:]
df_orig = df_orig.rename(columns={"SubjectID_new":"SubjectID"})

df_orig["SubjectID"] = df_orig["SubjectID"].astype(str) 
df_orig = df_orig[df_orig["SubjectID"].str.len() <= 8]   

df_orig

,lh_G_front_inf-Triangul_thickness,lh_G_front_middle_thickness,lh_G_front_sup_thickness,lh_G_oc-temp_lat-fusifor_thickness,lh_G_oc-temp_med-Lingual_thickness,lh_G_oc-temp_med-Parahip_thickness,lh_G_occipital_middle_thickness,lh_G_orbital_thickness,lh_G_pariet_inf-Angular_thickness,lh_G_pariet_inf-Supramar_thickness,lh_G_parietal_sup_thickness,lh_G_postcentral_thickness,lh_G_precentral_thickness,lh_G_rectus_thickness,lh_G_temp_sup-Lateral_thickness,lh_G_temp_sup-Plan_tempo_thickness,lh_G_temporal_inf_thickness,lh_G_temporal_middle_thickness,lh_Pole_occipital_thickness,lh_Pole_temporal_thickness,lh_S_calcarine_thickness,lh_S_central_thickness,lh_S_collat_transv_ant_thickness,lh_S_front_inf_thickness,lh_S_front_middle_thickness,lh_S_front_sup_thickness,lh_S_occipital_ant_thickness,lh_S_orbital-H_Shaped_thickness,lh_S_pericallosal_thickness,lh_S_postcentral_thickness,lh_S_precentral-inf-part_thickness,lh_S_precentral-sup-part_thickness,lh_S_temporal_inf_thickness,lh_S_temporal_sup_thickness,rh_G_cuneus_thickness,rh_G_front_middle_thickness,rh_G_front_sup_thickness,rh_G_oc-temp_lat-fusifor_thickness,rh_G_occipital_middle_thickness,rh_G_occipital_sup_thickness,rh_G_orbital_thickness,rh_G_pariet_inf-Angular_thickness,rh_G_pariet_inf-Supramar_thickness,rh_G_parietal_sup_thickness,rh_G_postcentral_thickness,rh_G_precentral_thickness,rh_G_precuneus_thickness,rh_G_temp_sup-Lateral_thickness,rh_G_temp_sup-Plan_tempo_thickness,rh_G_temporal_inf_thickness,rh_G_temporal_middle_thickness,rh_Pole_occipital_thickness,rh_S_calcarine_thickness,rh_S_central_thickness,rh_S_cingul-Marginalis_thickness,rh_S_front_inf_thickness,rh_S_front_middle_thickness,rh_S_front_sup_thickness,rh_S_interm_prim-Jensen_thickness,rh_S_oc-temp_lat_thickness,rh_S_occipital_ant_thickness,rh_S_parieto_occipital_thickness,rh_S_pericallosal_thickness,rh_S_postcentral_thickness,rh_S_precentral-inf-part_thickness,rh_S_precentral-sup-part_thickness,rh_S_temporal_sup_thickness,Year_initial_scan,Sex,Birthyear,Age,Site,SubjectID
0,2.859,2.994,3.053,3.310,2.248,2.847,2.846,3.016,2.873,3.261,2.815,2.368,2.955,3.441,3.265,2.718,3.326,3.215,2.260,3.297,2.075,2.159,3.082,2.661,2.565,2.774,2.719,3.068,2.288,2.521,2.617,2.518,2.518,2.803,2.051,2.741,2.932,3.033,2.811,2.532,3.070,2.830,2.593,2.522,2.183,2.853,2.670,3.282,2.650,3.318,3.051,2.059,2.016,1.869,2.466,2.446,2.393,2.753,2.170,2.914,2.665,2.533,1.965,2.227,2.672,2.561,2.735,2010,0.0,1950,60,11025.0,1533138
1,3.050,2.993,3.167,3.214,2.035,3.097,2.610,3.199,2.890,2.850,2.438,2.402,3.158,3.121,3.200,2.955,3.230,3.144,2.084,3.536,2.271,2.179,2.845,2.477,2.575,2.740,2.315,3.130,2.512,2.341,2.988,2.921,2.653,2.749,1.708,2.636,2.849,2.571,2.601,1.949,2.683,2.521,2.693,2.091,1.851,2.715,2.438,2.772,2.341,2.882,2.920,1.803,1.938,1.751,2.149,2.395,2.318,2.481,2.309,2.913,2.403,2.287,2.407,2.016,2.794,2.706,2.676,2008,0.0,1948,60,11025.0,1875529
2,2.575,2.677,3.002,3.026,1.646,2.861,2.427,2.801,2.714,2.690,2.413,2.417,2.714,3.094,3.407,2.641,3.045,2.815,1.720,3.630,1.797,2.054,2.869,2.533,2.426,2.691,2.417,2.788,1.654,2.334,2.728,2.652,2.406,2.483,1.783,2.876,3.247,3.404,2.820,2.442,3.032,2.761,2.790,2.552,2.109,2.785,2.880,3.645,2.914,3.305,3.205,1.982,2.115,2.104,2.437,2.509,2.570,2.631,2.253,2.494,2.663,2.461,1.793,2.397,2.537,2.547,2.684,2008,0.0,1946,62,11025.0,4758824
3,2.561,2.589,3.046,3.010,1.692,2.860,2.607,2.804,2.684,2.942,2.416,2.199,2.868,2.957,3.086,2.832,3.024,2.968,1.525,3.473,1.825,1.908,2.550,2.438,2.408,2.599,2.523,2.974,1.794,2.347,2.630,2.828,2.489,2.556,1.645,2.728,3.025,2.785,2.752,2.135,3.001,2.714,2.928,2.475,2.273,3.064,2.580,3.260,2.948,3.263,3.248,1.745,1.964,2.031,2.355,2.452,2.424,2.644,2.580,2.840,2.850,2.390,1.782,2.377,2.501,2.696,2.746,2010,0.0,1963,47,11025.0,5304207
4,2.969,2.940,3.229,3.124,2.212,3.408,2.742,2.924,2.904,3.024,2.618,2.415,3.072,3.012,3.519,3.272,3.212,3.048,2.120,3.517,2.194,2.189,2.410,2.545,2.484,2.924,2.548,3.221,1.768,2.493,2.956,2.789,2.703,2.615,1.941,2.994,3.273,3.154,2.863,2.361,3.173,3.089,3.175,2.624,2.523,3.298,2.846,3.533,3.129,3.452,3.257,2.056,2.197,2.179,2.784,2.651,2.580,2.774,2.511,2.972,2.727,2.504,1.927,2.579,2.863,2.843,2.829,2008,0.0,1963,45,11025.0,2747983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33937,2.743,2.868,3.188,2.943,2.110,3.555,2.797,3.222,2.769,2.906,2.640,2.353,3.131,3.296,3.397,2.566,3.142,3.166,2.171,3.407,2.089,2.331,2.827,2.521,2.507,2.780,2.715,3.190,1.574,2.510,3.044,2.823,2.658,2.616,2.035,2.790,3.109,3.161,2.911,2.330,3.026,2.949,3.087,2.684,2.369,3.151,2.844,3.451,2.885,3.390,3.256,1.972,2.233,2.139,2.739,2.502,2.538,2.770,2.529,2.691,2.462,2.643,1.648,2.351,2.870,2.696,2.851,2008,0.0,1957,51,11027.0,3463731
33938,2.620,2.807,2.965,3.055,2.270,3.299,2.677,2.676,2.654,2.676,2.252,2.307,3.124,2.628,3.195,2.800,3.260,3.154,2.154,3.160,2.124,2.113,2.992,2.359,2.290,2.524,2.269,2.693,2.459,2.172,2.441,2.503,2.518,2.464,2.021,2.567,2.969,3.053,3.009,2.358,2.519,2.695,2.847,2.251,2.222,2.947,2.645,3.180,2.760,3.185,3.106,2.156,1.963,2.019,2.358,2.262,2.249,2.531,2.380,2.611,2.452,2.193,1.963,2.245,2.408,2.523,2.536,2007,1.0,1960,47,11025.0,3814047
33939,2.838,2.639,2.796,2.808,2.121,3.124,2.659,2.616,2.545,2.881,2.317,2.183,2.529,2.565,2.985,2.763,3.056,3.055,2.062,3.396,2.078,1.976,2.878,2.452,2.309,2.516,2.511,2.831,1.827,2.149,2.524,2.486,2.118,2.644,1.889,2.628,2.890,2.969,2.723,2.378,2.732,2.804,2.930,2.169,2.367,2.625,2.537,3.286,2.971,2.983,3.393,2.150,2.198,2.052,2.359,2.381,2.367,2.500,2.720,2.362,2.649,2.299,2.461,2.173,2.552,2.408,2.845,2009,1.0,1940,69,11027.0,4851516
33940,3.115,3.135,3.192,3.233,2.275,3.257,2.900,2.910,3.113,3.277,2.645,2.541,3.204,2.806,3.624,3.119,3.564,3.445,2.102,3.450,2.117,2.410,2.971,2.827,2.834,2.822,2.352,3.226,2.106,2.549,2.923,2.912,2.882,2.911,1.787,2.816,3.220,3.445,2.992,2.566,3.062,3.142,3.232,2.916,2.435,2.779,3.090,3.562,3.259,3.350,3.597,2.312,2.224,2.175,2.621,2.630,2.499,2.722,3.248,2.844,2.475,2.448,2.071,2.475,2.698,2.665,3.171,2008,1.0,1961,47,11025.0,3626816
33941,2.951,3.025,3.244,3.234,2.130,3.051,2.834,2.884,3.021,2.952,2.659,2.610,3.027,3.217,3.416,2.959,3.376,3.444,2.087,3.824,2.044,2.461,3.062,2.662,2.546,3.033,2.603,2.850,2.122,2.795,2.982,2.998,3.046,2.871,1.783,2.755,2.896,2.856,2.540,2.161,2.635,2.706,2.772,2.498,2.119,2.531,2.488,3.201,2.470,3.001,3.237,1.969,1.947,2.355,2.972,2.641,2.612,2.923,2.766,2.420,2.654,2.396,1.608,2.645,2.755,2.845,2.866,2009,0.0,1949,60,11025.0,2420905

In [32]:
df_new["SubjectID"] = df_new["SubjectID"].astype(str) 
df_new = df_new[df_new["SubjectID"].str.len() <= 8]   
df_new

,SubjectID,3rd-Ventricle,4th-Ventricle,5th-Ventricle,Brain-Stem,CC_Anterior,CC_Central,CC_Mid_Anterior,CC_Mid_Posterior,CC_Posterior,CSF,Left-Accumbens-area,Left-Amygdala,Left-Caudate,Left-Cerebellum-Cortex,Left-Cerebellum-White-Matter,Left-Hippocampus,Left-Inf-Lat-Vent,Left-Lateral-Ventricle,Left-Pallidum,Left-Putamen,Left-Thalamus-Proper,Left-VentralDC,Left-WM-hypointensities,Left-choroid-plexus,Left-non-WM-hypointensities,Left-vessel,Optic-Chiasm,Right-Accumbens-area,Right-Amygdala,Right-Caudate,Right-Cerebellum-Cortex,Right-Cerebellum-White-Matter,Right-Hippocampus,Right-Inf-Lat-Vent,Right-Lateral-Ventricle,Right-Pallidum,Right-Putamen,Right-Thalamus-Proper,Right-VentralDC,Right-WM-hypointensities,Right-choroid-plexus,Right-non-WM-hypointensities,Right-vessel,WM-hypointensities,non-WM-hypointensities,Left-Thalamus,Right-Thalamus
0,1533138,1042.8,1818.5,0.0,19411.7,843.2,440.4,454.1,588.9,942.0,849.3,326.5,1158.6,2981.5,52123.0,15121.2,3832.5,217.1,7040.0,1829.0,4371.3,6288.0,3582.8,0.0,474.9,0.0,71.3,198.3,443.8,1599.6,3194.4,55420.0,13841.5,3737.6,282.4,6787.7,1694.5,4255.5,6420.0,3397.3,0.0,405.8,0.0,23.2,2197.7,0.0,NaN,NaN
1,1875529,3248.4,2777.2,0.0,22865.0,739.7,407.3,397.8,432.5,869.5,965.3,311.9,1539.0,3433.3,54364.3,14494.0,3902.6,808.9,26064.3,2141.6,5031.0,6322.9,4674.2,0.0,1103.5,0.0,64.8,295.9,374.5,1881.2,3844.5,56909.3,14260.8,4321.8,360.8,12101.7,2006.3,5113.6,6855.6,4324.8,0.0,909.3,0.0,29.9,2288.2,0.0,NaN,NaN
2,4758824,1459.8,1194.8,0.0,19145.9,1050.7,478.7,450.6,574.6,1099.9,1013.6,350.0,1353.6,3065.9,50143.7,13891.9,3840.5,191.2,13826.6,1888.6,3919.1,6328.4,3640.8,0.0,633.0,0.0,60.7,169.1,458.0,1630.4,3040.3,48588.0,12370.2,3928.0,248.5,12956.1,1704.4,4027.4,6274.4,3645.9,0.0,500.8,0.0,71.5,1448.0,0.0,NaN,NaN
3,5304207,968.3,1442.7,0.0,21161.8,910.5,718.3,660.4,652.7,1142.6,821.1,491.8,1687.7,2637.0,54562.0,15344.0,4004.2,127.0,7498.7,1756.7,4757.7,7132.8,3505.2,0.0,298.2,0.0,13.2,94.0,447.6,1829.9,2670.7,57484.2,15011.3,4266.6,551.0,5207.7,1823.1,4624.6,6374.3,3564.4,0.0,303.4,0.0,48.0,858.6,0.0,NaN,NaN
4,2747983,860.3,1447.2,0.0,21304.0,882.6,559.7,624.6,612.5,923.9,932.2,410.9,1610.0,3096.7,53063.9,16440.8,4172.9,283.6,7427.7,1896.8,4584.8,6667.1,3869.6,0.0,371.0,0.0,69.5,156.6,599.5,1826.7,3119.7,55716.8,14284.4,4280.3,279.5,8587.3,1824.7,4895.9,6893.6,3838.9,0.0,540.0,0.0,68.4,694.2,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37945,3463731,962.3,1154.3,0.0,21464.8,785.9,724.0,564.0,498.5,988.9,837.3,330.9,1354.4,2589.3,46837.7,14219.9,3517.5,200.1,5237.2,2088.1,5063.4,6898.2,3834.2,0.0,348.7,0.0,27.1,138.8,441.6,1447.1,2735.9,49112.9,13655.3,3615.6,184.7,5069.1,1948.0,4886.7,6547.4,3755.6,0.0,439.9,0.0,0.0,885.3,0.0,NaN,NaN
37946,3814047,1182.0,1445.8,0.0,25059.0,951.8,711.9,825.6,743.9,1191.1,1175.0,618.2,2257.9,3929.0,71327.8,18528.9,4900.1,263.4,7488.6,2399.3,5625.6,7573.9,4601.3,0.0,569.0,0.0,44.8,172.4,712.6,2356.3,4018.9,73952.0,17395.7,5061.8,200.3,7450.8,2218.5,5947.9,7799.1,4495.4,0.0,542.9,0.0,28.6,1157.0,0.0,NaN,NaN
37947,4851516,2345.8,1714.8,0.0,20643.3,616.9,321.2,313.5,278.4,828.3,1258.4,393.1,1493.3,3634.8,62900.5,15583.3,4165.1,651.9,17109.3,2324.8,4856.9,6237.1,4259.9,0.0,1393.8,0.0,74.8,290.1,463.4,1671.7,3789.5,66154.3,15070.7,3852.9,767.5,18407.2,2230.5,5115.0,6231.3,4217.3,0.0,1193.6,0.0,31.2,2548.0,0.0,NaN,NaN
37948,3626816,852.9,858.6,0.0,24009.2,755.2,554.5,635.7,572.3,1020.3,712.2,552.7,1870.8,3729.8,55355.3,16060.6,4526.1,65.8,6791.9,2325.1,6058.7,8068.6,4196.4,0.0,338.5,0.0,164.8,166.9,558.0,2026.1,3848.6,58602.5,15405.8,4711.2,345.6,5708.0,2154.0,6162.5,8027.5,4185.9,0.0,415.3,0.0,112.8,971.6,0.0,NaN,NaN
37949,2420905,3531.1,3100.4,0.0,20448.3,794.9,811.0,567.5,588.3,948.2,1813.1,262.6,1667.0,3531.0,60151.5,14175.0,4200.4,1302.7,34828.9,2031.7,4675.1,5771.6,3982.7,0.0,1036.6,0.0,37.1,326.8,428.8,1714.7,3421.1,60502.4,13785.5,4318.6,963.9,34009.1,1829.9,4789.3,6216.1,3982.1,0.0,797.9,0.0,40.1,2964.3,0.0,NaN,NaN

In [33]:
df_orig["SubjectID"] = df_orig["SubjectID"].astype(int)
df_new["SubjectID"] = df_new["SubjectID"].astype(int)

df_orig = df_orig.merge(df_new, on="SubjectID", how="left", suffixes=('', ''))

,lh_G_front_inf-Triangul_thickness,lh_G_front_middle_thickness,lh_G_front_sup_thickness,lh_G_oc-temp_lat-fusifor_thickness,lh_G_oc-temp_med-Lingual_thickness,lh_G_oc-temp_med-Parahip_thickness,lh_G_occipital_middle_thickness,lh_G_orbital_thickness,lh_G_pariet_inf-Angular_thickness,lh_G_pariet_inf-Supramar_thickness,lh_G_parietal_sup_thickness,lh_G_postcentral_thickness,lh_G_precentral_thickness,lh_G_rectus_thickness,lh_G_temp_sup-Lateral_thickness,lh_G_temp_sup-Plan_tempo_thickness,lh_G_temporal_inf_thickness,lh_G_temporal_middle_thickness,lh_Pole_occipital_thickness,lh_Pole_temporal_thickness,lh_S_calcarine_thickness,lh_S_central_thickness,lh_S_collat_transv_ant_thickness,lh_S_front_inf_thickness,lh_S_front_middle_thickness,lh_S_front_sup_thickness,lh_S_occipital_ant_thickness,lh_S_orbital-H_Shaped_thickness,lh_S_pericallosal_thickness,lh_S_postcentral_thickness,lh_S_precentral-inf-part_thickness,lh_S_precentral-sup-part_thickness,lh_S_temporal_inf_thickness,lh_S_temporal_sup_thickness,rh_G_cuneus_thickness,rh_G_front_middle_thickness,rh_G_front_sup_thickness,rh_G_oc-temp_lat-fusifor_thickness,rh_G_occipital_middle_thickness,rh_G_occipital_sup_thickness,rh_G_orbital_thickness,rh_G_pariet_inf-Angular_thickness,rh_G_pariet_inf-Supramar_thickness,rh_G_parietal_sup_thickness,rh_G_postcentral_thickness,rh_G_precentral_thickness,rh_G_precuneus_thickness,rh_G_temp_sup-Lateral_thickness,rh_G_temp_sup-Plan_tempo_thickness,rh_G_temporal_inf_thickness,rh_G_temporal_middle_thickness,rh_Pole_occipital_thickness,rh_S_calcarine_thickness,rh_S_central_thickness,rh_S_cingul-Marginalis_thickness,rh_S_front_inf_thickness,rh_S_front_middle_thickness,rh_S_front_sup_thickness,rh_S_interm_prim-Jensen_thickness,rh_S_oc-temp_lat_thickness,rh_S_occipital_ant_thickness,rh_S_parieto_occipital_thickness,rh_S_pericallosal_thickness,rh_S_postcentral_thickness,rh_S_precentral-inf-part_thickness,rh_S_precentral-sup-part_thickness,rh_S_temporal_sup_thickness,Year_initial_scan,Sex,Birthyear,Age,Site,SubjectID,3rd-Ventricle,4th-Ventricle,5th-Ventricle,Brain-Stem,CC_Anterior,CC_Central,CC_Mid_Anterior,CC_Mid_Posterior,CC_Posterior,CSF,Left-Accumbens-area,Left-Amygdala,Left-Caudate,Left-Cerebellum-Cortex,Left-Cerebellum-White-Matter,Left-Hippocampus,Left-Inf-Lat-Vent,Left-Lateral-Ventricle,Left-Pallidum,Left-Putamen,Left-Thalamus-Proper,Left-VentralDC,Left-WM-hypointensities,Left-choroid-plexus,Left-non-WM-hypointensities,Left-vessel,Optic-Chiasm,Right-Accumbens-area,Right-Amygdala,Right-Caudate,Right-Cerebellum-Cortex,Right-Cerebellum-White-Matter,Right-Hippocampus,Right-Inf-Lat-Vent,Right-Lateral-Ventricle,Right-Pallidum,Right-Putamen,Right-Thalamus-Proper,Right-VentralDC,Right-WM-hypointensities,Right-choroid-plexus,Right-non-WM-hypointensities,Right-vessel,WM-hypointensities,non-WM-hypointensities,Left-Thalamus,Right-Thalamus
0,2.859,2.994,3.053,3.310,2.248,2.847,2.846,3.016,2.873,3.261,2.815,2.368,2.955,3.441,3.265,2.718,3.326,3.215,2.260,3.297,2.075,2.159,3.082,2.661,2.565,2.774,2.719,3.068,2.288,2.521,2.617,2.518,2.518,2.803,2.051,2.741,2.932,3.033,2.811,2.532,3.070,2.830,2.593,2.522,2.183,2.853,2.670,3.282,2.650,3.318,3.051,2.059,2.016,1.869,2.466,2.446,2.393,2.753,2.170,2.914,2.665,2.533,1.965,2.227,2.672,2.561,2.735,2010,0.0,1950,60,11025.0,1533138,1042.8,1818.5,0.0,19411.7,843.2,440.4,454.1,588.9,942.0,849.3,326.5,1158.6,2981.5,52123.0,15121.2,3832.5,217.1,7040.0,1829.0,4371.3,6288.0,3582.8,0.0,474.9,0.0,71.3,198.3,443.8,1599.6,3194.4,55420.0,13841.5,3737.6,282.4,6787.7,1694.5,4255.5,6420.0,3397.3,0.0,405.8,0.0,23.2,2197.7,0.0,NaN,NaN
1,3.050,2.993,3.167,3.214,2.035,3.097,2.610,3.199,2.890,2.850,2.438,2.402,3.158,3.121,3.200,2.955,3.230,3.144,2.084,3.536,2.271,2.179,2.845,2.477,2.575,2.740,2.315,3.130,2.512,2.341,2.988,2.921,2.653,2.749,1.708,2.636,2.849,2.571,2.601,1.949,2.683,2.521,2.693,2.091,1.851,2.715,2.438,2.772,2.341,2.882,2.920,1.803,1.938,1.751,2.149,2.395,2.318,2.481,2.309,2.913,2.403,2.287,2.407,2.016,2.794,2.706,2.676,2008,0.0,1948,60,11025.0,1875529,3248.4,2777.2,0.0,22865.0,739.7,407.3,397.8,432.5,869.5,965.3,311.9,1539.0,3433.3,54364.3,14494.0,3902.6,808.9,26064.3,2141.6,5031.0,6322.9,4674.2,0.0,1103.5,0.0,64.8,295.9,374.5,1881.2,3844.5,56909.3,14260.8,4321.8,360.8,12101.7,2006.3,5113.6,6855.6,4324.8,0.0,909.3,0.0,29.9,2288.2,0.0,NaN,NaN
2,2.575,2.677,3.002,3.026,1.646,2.861,2.427,2.801,2.714,2.690,2.413,2.417,2.714,3.094,3.407,2.641,3.045,2.815,1.720,3.630,1.797,2.054,2.869,2.533,2.426,2.691,2.417,2.788,1.654,2.334,2.728,2.652,2.406,2.483,1.783,2.876,3.247,3.404,2.820,2.442,3.032,2.761,2.790,2.552,2.109,2.785,2.880,3.645,2.914,3.305,3.205,1.982,2.115,2.104,2.437,2.509,2.570,2.631,2.253,2.494,2.663,2.461,1.793,2.397,2.537,2.547,2.684,2008,0.0,1946,62,11025.0,4758824,1459.8,1194.8,0.0,19145.9,1050.7,478.7,450.6,574.6,1099.9,1013.6,350.0,1353.6,3065.9,50143.7,13891.9,3840.5,191.2,13826.6,1888.6,3919.1,6328.4,3640.8,0.0,633.0,0.0,60.7,169.1,458.0,1630.4,3040.3,48588.0,12370.2,3928.0,248.5,12956.1,1704.4,4027.4,6274.4,3645.9,0.0,500.8,0.0,71.5,1448.0,0.0,NaN,NaN
3,2.561,2.589,3.046,3.010,1.692,2.860,2.607,2.804,2.684,2.942,2.416,2.199,2.868,2.957,3.086,2.832,3.024,2.968,1.525,3.473,1.825,1.908,2.550,2.438,2.408,2.599,2.523,2.974,1.794,2.347,2.630,2.828,2.489,2.556,1.645,2.728,3.025,2.785,2.752,2.135,3.001,2.714,2.928,2.475,2.273,3.064,2.580,3.260,2.948,3.263,3.248,1.745,1.964,2.031,2.355,2.452,2.424,2.644,2.580,2.840,2.850,2.390,1.782,2.377,2.501,2.696,2.746,2010,0.0,1963,47,11025.0,5304207,968.3,1442.7,0.0,21161.8,910.5,718.3,660.4,652.7,1142.6,821.1,491.8,1687.7,2637.0,54562.0,15344.0,4004.2,127.0,7498.7,1756.7,4757.7,7132.8,3505.2,0.0,298.2,0.0,13.2,94.0,447.6,1829.9,2670.7,57484.2,15011.3,4266.6,551.0,5207.7,1823.1,4624.6,6374.3,3564.4,0.0,303.4,0.0,48.0,858.6,0.0,NaN,NaN
4,2.969,2.940,3.229,3.124,2.212,3.408,2.742,2.924,2.904,3.024,2.618,2.415,3.072,3.012,3.519,3.272,3.212,3.048,2.120,3.517,2.194,2.189,2.410,2.545,2.484,2.924,2.548,3.221,1.768,2.493,2.956,2.789,2.703,2.615,1.941,2.994,3.273,3.154,2.863,2.361,3.173,3.089,3.175,2.624,2.523,3.298,2.846,3.533,3.129,3.452,3.257,2.056,2.197,2.179,2.784,2.651,2.580,2.774,2.511,2.972,2.727,2.504,1.927,2.579,2.863,2.843,2.829,2008,0.0,1963,45,11025.0,2747983,860.3,1447.2,0.0,21304.0,882.6,559.7,624.6,612.5,923.9,932.2,410.9,1610.0,3096.7,53063.9,16440.8,4172.9,283.6,7427.7,1896.8,4584.8,6667.1,3869.6,0.0,371.0,0.0,69.5,156.6,599.5,1826.7,3119.7,55716.8,14284.4,4280.3,279.5,8587.3,1824.7,4895.9,6893.6,3838.9,0.0,540.0,0.0,68.4,694.2,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33937,2.743,2.868,3.188,2.943,2.110,3.555,2.797,3.222,2.769,2.906,2.640,2.353,3.131,3.296,3.397,2.566,3.142,3.166,2.171,3.407,2.089,2.331,2.827,2.521,2.507,2.780,2.715,3.190,1.574,2.510,3.044,2.823,2.658,2.616,2.035,2.790,3.109,3.161,2.911,2.330,3.026,2.949,3.087,2.684,2.369,3.151,2.844,3.451,2.885,3.390,3.256,1.972,2.233,2.139,2.739,2.502,2.538,2.770,2.529,2.691,2.462,2.643,1.648,2.351,2.870,2.696,2.851,2008,0.0,1957,51,11027.0,3463731,962.3,1154.3,0.0,21464.8,785.9,724.0,564.0,498.5,988.9,837.3,330.9,1354.4,2589.3,46837.7,14219.9,3517.5,200.1,5237.2,2088.1,5063.4,6898.2,3834.2,0.0,348.7,0.0,27.1,138.8,441.6,1447.1,2735.9,49112.9,13655.3,3615.6,184.7,5069.1,1948.0,4886.7,6547.4,3755.6,0.0,439.9,0.0,0.0,885.3,0.0,NaN,NaN
33938,2.620,2.807,2.965,3.055,2.270,3.299,2.677,2.676,2.654,2.676,2.252,2.307,3.124,2.628,3.195,2.800,3.260,3.154,2.154,3.160,2.124,2.113,2.992,2.359,2.290,2.524,2.269,2.693,2.459,2.172,2.441,2.503,2.518,2.464,2.021,2.567,2.969,3.053,3.009,2.358,2.519,2.695,2.847,2.251,2.222,2.947,2.645,3.180,2.760,3.185,3.106,2.156,1.963,2.019,2.358,2.262,2.249,2.531,2.380,2.611,2.452,2.193,1.963,2.245,2.408,2.523,2.536,2007,1.0,1960,47,11025.0,3814047,1182.0,1445.8,0.0,25059.0,951.8,711.9,825.6,743.9,1191.1,1175.0,618.2,2257.9,3929.0,71327.8,18528.9,4900.1,263.4,7488.6,2399.3,5625.6,7573.9,4601.3,0.0,569.0,0.0,44.8,172.4,712.6,2356.3,4018.9,73952.0,17395.7,5061.8,200.3,7450.8,2218.5,5947.9,7799.1,4495.4,0.0,542.9,0.0,28.6,1157.0,0.0,NaN,NaN
33939,2.838,2.639,2.796,2.808,2.121,3.124,2.659,2.616,2.545,2.881,2.317,2.183,2.529,2.565,2.985,2.763,3.056,3.055,2.062,3.396,2.078,1.976,2.878,2.452,2.309,2.516,2.511,2.831,1.827,2.149,2.524,2.486,2.118,2.644,1.889,2.628,2.890,2.969,2.723,2.378,2.732,2.804,2.930,2.169,2.367,2.625,2.537,3.286,2.971,2.983,3.393,2.150,2.198,2.052,2.359,2.381,2.367,2.500,2.720,2.362,2.649,2.299,2.461,2.173,2.552,2.408,2.845,2009,1.0,1940,69,11027.0,4851516,2345.8,1714.8,0.0,20643.3,616.9,321.2,313.5,278.4,828.3,1258.4,393.1,1493.3,3634.8,62900.5,15583.3,4165.1,651.9,17109.3,2324.8,4856.9,6237.1,4259.9,0.0,1393.8,0.0,74.8,290.1,463.4,1671.7,3789.5,66154.3,15070.7,3852.9,767.5,18407.2,2230.5,5115.0,6231.3,4217.3,0.0,1193.6,0.0,31.2,2548.0,0.0,NaN,NaN
33940,3.115,3.135,3.192,3.233,2.275,3.257,2.900,2.910,3.113,3.277,2.645,2.541,3.204,2.806,3.624,3.119,3.564,3.445,2.102,3.450,2.117,2.410,2.971,2.827,2.834,2.822,2.352,3.226,2.106,2.549,2.923,2.912,2.882,2.911,1.787,2.816,3.220,3.445,2.992,2.566,3.062,3.142,3.232,2.916,2.435,2.779,3.090,3.562,3.259,3.350,3.597,2.312,2.224,2.175,2.621,2.630,2.499,2.722,3.248,2.844,2.475,2.448,2.071,2.475,2.698,2.665,3.171,2008,1.0,1961,47,11025.0,3626816,852.9,858.6,0.0,24009.2,755.2,554.5,635.7,572.3,1020.3,712.2,552.7,1870.8,3729.8,55355.3,16060.6,4526.1,65.8,6791.9,2325.1,6058.7,8068.6,4196.4,0.0,338.5,0.0,164.8,166.9,558.0,2026.1,3848.6,58602.5,15405.8,4711.2,345.6,5708.0,2154.0,6162.5,8027.5,4185.9,0.0,415.3,0.0,112.8,971.6,0.0,NaN,NaN
33941,2.951,3.025,3.244,3.234,2.130,3.051,2.834,2.884,3.021,2.952,2.659,2.610,3.027,3.217,3.416,2.959,3.376,3.444,2.087,3.824,2.044,2.461,3.062,2.662,2.546,3.033,2.603,2.850,2.122,2.795,2.982,2.998,3.046,2.871,1.783,2.755,2.896,2.856,2.540,2.161,2.635,2.706,2.772,2.498,2.119,2.531,2.488,3.201,2.470,3.001,3.237,1.969,1.947,2.355,2.972,2.641,2.612,2.923,2.766,2.420,2.654,2.396,1.608,2.645,2.755,2.845,2.866,2009,0.0,1949,60,11025.0,2420905,3531.1,3100.4,0.0,20448.3,794.9,811.0,567.5,588.3,948.2,1813.1,262.6,1667.0,3531.0,60151.5,14175.0,4200.4,1302.7,34828.9,2031.7,4675.1,5771.6,3982.7,0.0,1036.6,0.0,37.1,326.8,428.8,1714.7,3421.1,60502.4,13785.5,4318.6,963.9,34009.1,1829.9,4789.3,6216.1,3982.1,0.0,797.9,0.0,40.1,2964.3,0.0,NaN,NaN

In [35]:
df_orig.to_csv("Final_data_correct.csv")

In [34]:
df_oasis = pd.read_csv("/home/preclineu/quirom/Desktop/internship/Normative-Models-and-VAE/logs/data_prep/Oasis3_data.csv")
df_oasis

,Unnamed: 0,SubjectID,3rd-Ventricle,4th-Ventricle,5th-Ventricle,Brain-Stem,CC_Anterior,CC_Central,CC_Mid_Anterior,CC_Mid_Posterior,CC_Posterior,CSF,Left-Accumbens-area,Left-Amygdala,Left-Caudate,Left-Cerebellum-Cortex,Left-Cerebellum-White-Matter,Left-Hippocampus,Left-Inf-Lat-Vent,Left-Lateral-Ventricle,Left-Pallidum,Left-Putamen,Left-VentralDC,Left-WM-hypointensities,Left-choroid-plexus,Left-non-WM-hypointensities,Left-vessel,Optic-Chiasm,Right-Accumbens-area,Right-Amygdala,Right-Caudate,Right-Cerebellum-Cortex,Right-Cerebellum-White-Matter,Right-Hippocampus,Right-Inf-Lat-Vent,Right-Lateral-Ventricle,Right-Pallidum,Right-Putamen,Right-VentralDC,Right-WM-hypointensities,Right-choroid-plexus,Right-non-WM-hypointensities,Right-vessel,WM-hypointensities,non-WM-hypointensities,lh_G_front_inf-Opercular_thickness,lh_G_front_inf-Triangul_thickness,lh_G_front_middle_thickness,lh_G_front_sup_thickness,lh_G_oc-temp_lat-fusifor_thickness,lh_G_oc-temp_med-Lingual_thickness,lh_G_oc-temp_med-Parahip_thickness,lh_G_occipital_middle_thickness,lh_G_orbital_thickness,lh_G_pariet_inf-Angular_thickness,lh_G_pariet_inf-Supramar_thickness,lh_G_parietal_sup_thickness,lh_G_postcentral_thickness,lh_G_precentral_thickness,lh_G_rectus_thickness,lh_G_temp_sup-Lateral_thickness,lh_G_temp_sup-Plan_tempo_thickness,lh_G_temporal_inf_thickness,lh_G_temporal_middle_thickness,lh_Pole_occipital_thickness,lh_Pole_temporal_thickness,lh_S_calcarine_thickness,lh_S_central_thickness,lh_S_collat_transv_ant_thickness,lh_S_front_inf_thickness,lh_S_front_middle_thickness,lh_S_front_sup_thickness,lh_S_occipital_ant_thickness,lh_S_orbital-H_Shaped_thickness,lh_S_pericallosal_thickness,lh_S_postcentral_thickness,lh_S_precentral-inf-part_thickness,lh_S_precentral-sup-part_thickness,lh_S_temporal_inf_thickness,lh_S_temporal_sup_thickness,rh_G_cuneus_thickness,rh_G_front_middle_thickness,rh_G_front_sup_thickness,rh_G_oc-temp_lat-fusifor_thickness,rh_G_occipital_middle_thickness,rh_G_occipital_sup_thickness,rh_G_orbital_thickness,rh_G_pariet_inf-Angular_thickness,rh_G_pariet_inf-Supramar_thickness,rh_G_parietal_sup_thickness,rh_G_postcentral_thickness,rh_G_precentral_thickness,rh_G_precuneus_thickness,rh_G_temp_sup-Lateral_thickness,rh_G_temp_sup-Plan_tempo_thickness,rh_G_temporal_inf_thickness,rh_G_temporal_middle_thickness,rh_Pole_occipital_thickness,rh_S_calcarine_thickness,rh_S_central_thickness,rh_S_cingul-Marginalis_thickness,rh_S_front_inf_thickness,rh_S_front_middle_thickness,rh_S_front_sup_thickness,rh_S_interm_prim-Jensen_thickness,rh_S_oc-temp_lat_thickness,rh_S_occipital_ant_thickness,rh_S_parieto_occipital_thickness,rh_S_pericallosal_thickness,rh_S_postcentral_thickness,rh_S_precentral-inf-part_thickness,rh_S_precentral-sup-part_thickness,rh_S_temporal_sup_thickness,Sex,Age,Site,Diagnosis
0,0,OAS30001_MR_d0129,743.3,1461.3,0.0,21397.6,782.3,512.0,478.5,485.7,885.7,823.2,400.8,1450.8,3030.6,44219.8,15701.3,3750.8,346.9,5436.4,985.4,4515.9,3496.6,0.0,1056.4,0.0,42.0,164.8,467.5,1385.8,2874.8,44602.1,16298.9,3928.1,409.4,3741.7,1405.4,4404.8,3693.3,0.0,1178.1,0.0,57.9,1121.8,26.4,2.647,2.370,2.500,2.850,2.674,2.005,3.281,2.611,2.622,2.462,2.658,2.413,1.995,2.732,2.371,3.220,2.739,3.027,2.926,2.237,3.692,1.734,1.918,2.528,2.260,2.186,2.420,2.423,2.764,2.388,2.126,2.473,2.565,2.443,2.394,1.827,2.379,2.767,2.763,2.558,2.193,2.501,2.637,2.625,2.441,2.123,2.707,2.640,3.083,2.497,2.918,2.951,1.980,1.784,1.916,2.310,2.220,2.149,2.286,2.457,2.532,2.573,2.306,2.220,2.152,2.330,2.357,2.424,0.0,66.0,401,0.0
1,1,OAS30001_MR_d0757,750.8,1242.4,0.0,21289.2,767.5,473.2,491.0,496.8,870.1,858.0,279.9,1510.7,2944.1,44712.0,16010.6,3698.6,318.0,5601.5,786.1,4228.2,3282.3,0.0,1188.8,0.0,39.1,174.2,480.9,1368.4,2856.1,45128.6,16260.2,3949.6,331.5,3814.2,1349.4,4328.1,3306.7,0.0,1594.6,0.0,48.2,1297.5,15.2,2.641,2.286,2.371,2.751,2.684,1.930,3.399,2.619,2.623,2.438,2.643,2.263,2.041,2.661,2.412,3.165,2.546,2.965,2.960,2.186,3.541,1.662,1.943,2.379,2.041,1.923,2.241,2.399,2.601,2.323,2.001,2.363,2.330,2.347,2.382,1.737,2.227,2.694,2.776,2.680,2.117,2.613,2.366,2.307,2.315,1.929,2.424,2.441,3.026,2.159,3.004,2.859,1.886,1.636,1.687,2.238,1.987,1.944,2.225,2.270,2.655,2.572,2.097,2.394,1.926,2.215,2.282,2.227,0.0,67.0,401,0.0
2,2,OAS30001_MR_d2430,928.3,1795.6,0.0,20557.0,760.8,459.0,421.6,416.7,857.1,929.4,347.5,1293.3,2967.5,41359.6,14715.0,3258.6,554.2,6959.9,981.3,4789.4,3306.0,0.0,1172.9,0.0,63.4,197.5,503.1,1543.4,2816.5,40559.0,15734.8,3847.3,430.2,5102.2,1291.5,4459.3,3372.0,0.0,1530.3,0.0,116.8,1542.6,39.0,2.570,2.291,2.364,2.667,2.605,1.996,3.255,2.545,2.510,2.405,2.516,2.263,2.005,2.571,2.088,2.928,2.340,2.864,2.790,2.219,3.367,1.692,1.895,2.407,2.018,2.071,2.150,2.336,2.350,2.595,2.037,2.248,2.250,2.231,2.303,1.818,2.392,2.631,2.841,2.569,2.170,2.524,2.496,2.492,2.302,2.038,2.565,2.549,3.040,2.510,2.922,2.927,1.966,1.822,1.809,2.115,2.156,2.127,2.157,2.314,2.445,2.570,2.221,2.067,2.056,2.211,2.128,2.387,0.0,72.0,402,0.0
3,3,OAS30001_MR_d3132,900.7,1636.4,0.0,21382.7,756.3,422.5,434.5,448.3,861.0,903.0,412.3,1262.8,2872.6,41851.6,15143.7,3288.5,546.7,7174.2,1065.6,4070.2,3441.5,0.0,1267.6,0.0,57.6,226.1,459.6,1334.0,2806.3,41855.1,16942.9,3573.4,469.8,5416.6,1281.6,4602.9,3476.8,0.0,1552.6,0.0,71.0,1393.6,51.0,2.634,2.515,2.470,2.743,2.634,1.948,3.226,2.517,2.581,2.369,2.506,2.360,2.009,2.657,2.449,2.948,2.339,2.957,2.971,2.154,3.454,1.714,1.900,2.358,2.041,2.061,2.240,2.189,2.458,2.539,2.018,2.408,2.449,2.356,2.287,1.713,2.356,2.656,2.749,2.552,2.091,2.723,2.518,2.558,2.290,2.095,2.601,2.405,2.995,2.432,2.949,2.914,1.939,1.687,1.877,2.211,2.115,2.042,2.290,2.197,2.558,2.581,2.139,2.330,2.041,2.248,2.235,2.361,0.0,74.0,403,0.0
4,4,OAS30002_MR_d0653,2377.4,1992.3,7.4,25286.3,796.0,399.9,407.2,362.7,932.5,1328.7,368.2,1628.2,4520.8,47648.2,13612.1,4311.5,709.0,17479.9,1778.2,5093.0,4093.6,0.0,1409.3,0.0,114.1,286.2,527.5,1724.3,4889.2,50742.9,14329.4,4548.8,537.0,19603.4,1745.5,5097.7,4289.3,0.0,1918.2,0.0,131.2,3361.0,54.6,2.761,2.590,2.672,2.692,2.913,2.180,3.494,2.597,2.534,2.517,2.545,2.249,2.238,2.699,2.539,3.254,2.553,2.967,2.990,2.032,3.467,1.871,1.917,2.585,2.217,2.101,2.401,2.224,2.266,2.558,1.992,2.430,2.162,2.337,2.431,1.768,2.500,2.787,3.095,2.633,1.964,2.587,2.478,2.715,2.162,2.125,2.628,2.326,3.201,2.648,3.173,2.929,2.087,1.737,1.886,2.164,2.200,1.924,2.292,2.030,2.532,2.422,2.026,1.931,1.966,2.299,2.293,2.550,1.0,69.0,401,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1888,2039,OAS31168_MR_d2526,1552.9,2696.6,0.0,20124.8,752.7,366.6,406.2,350.2,909.4,1133.0,367.9,1686.7,4065.8,41790.2,11833.0,2955.9,1762.7,20042.0,1532.2,5569.4,3479.4,0.0,1846.3,0.0,148.7,263.0,698.0,1861.4,4080.0,45463.5,12809.3,3612.9,924.0,17174.5,1535.2,5534.0,3423.1,0.0,2344.7,0.0,190.8,6676.3,82.1,2.434,2.171,2.580,2.647,3.086,1.867,2.769,2.650,2.526,2.516,2.475,2.249,2.174,2.664,2.373,2.664,2.437,3.022,2.852,2.006,2.932,1.860,1.795,2.396,2.103,2.128,2.315,2.201,2.343,2.380,2.005,2.477,2.359,2.458,2.317,1.826,2.428,2.729,2.917,2.418,1.932,2.816,2.505,2.484,2.279,1.826,2.683,2.354,2.928,2.168,3.205,2.914,2.135,1.747,1.746,2.214,1.986,2.038,2.365,2.184,2.603,2.134,1.921,2.012,1.810,2.171,2.450,2.318,1.0,72.0,403,0.0
1889,2040,OAS31169_MR_d0620,3273.6,3007.1,0.0,18279.0,951.5,379.6,340.6,335.7,1016.9,1391.1,278.5,1316.4,3124.2,46698.9,12487.5,3418.1,1461.0,29090.1,1470.8,5227.5,3333.8,0.0,1696.2,0.0,181.0,204.8,395.9,1324.7,3422.0,48510.0,12185.4,3410.4,1108.4,32552.8,1353.3,4806.3,3396.5,0.0,2738.7,0.0,146.8,3117.2,54.9,2.922,2.710,2.665,2.882,2.594,1.943,3.011,2.360,2.638,2.530,2.677,2.335,2.336,2.840,2.365,3.122,2.606,2.844,2.699,2.130,3.235,1.794,1.911,2.130,2.231,2.215,2.460,1.981,2.146,1.910,2.109,2.391,2.434,2.176,2.299,1.860,2.703,2.832,3.033,2.649,2.303,2.648,2.685,2.711,2.464,2.385,2.726,2.555,3.266,2.686,2.830,2.965,2.111,1.660,1.928,2.324,2.124,2.041,2.373,2.184,2.359,2.351,2.099,2.602,2.221,2.280,2.456,2.414,0.0,65.0,401,0.0
1890,2041,OAS31170_MR_d2410,1245.6,2124.2,0.0,18019.3,707.0,350.8,348.2,293.1,904.0,1158.1,615.7,1220.7,3200.5,37779.0,12642.8,2081.1,852.9,9687.5,1142.0,4708.9,3039.9,0.0,1324.0,0.0,96.5,306.7,540.6,1517.7,3390.1,41136.2,13748.6,2420.2,638.5,9610.1,1245.2,4562.3,3170.4,0.0,1835.2,0.0,104.5,2007.8,35.1,2.586,2.271,2.415,2.727,2.525,1.824,2.563,2.212,2.529,2.216,2.468,2.144,1.984,2.492,2.369,2.824,2.254,2.581,2.657,1.723,3.053,1.565,1.680,2.143,2.078,1.918,2.235,1.880,2.611,2.236,1.947,2.153,2.153,2.154,2.078,1.629,2.421,2.627,2.661,2.228,1.988,2.345,2.386,2.462,2.217,2.013,2.533,2.421,2.710,2.244,2.622,2.752,1.801,1.714,1.771,2.085,1.886,1.987,2.261,1.851,2.295,1.881,2.101,2.182,1.803,2.264,2.114,2.200,0.0,71.0,401,1.0
1891,2042,OAS31172_MR_d0407,2450.0,1317.7,5.3,18504.3,757.5,302.3,306.4,256.1,969.6,1310.8,330.9,1177.0,3127.8,37769.4,13136.8,4009.4,692.8,18445.3,1081.7,3172.8,3545.8,0.0,1902.6,0.0,45.4,311.0,434.8,1304.4,3825.6,40033.0,12346.7,4193.5,349.1,16821.0,1330.9,3476.4,3558.3,0.0,3555.4,0.0,52.7,3143.4,130.9,2.576,2.343,2.314,2.526,2.255,1.878,2.967,2.229,2.773,2.301,2.101,2.122,1.831,2.427,2.406,2.864,1.983,2.641,2.410,1.773,3.175,1.674,1.584,2.497,2.091,2.026,2.262,2.006,2.991,0.952,1.935,2.120,2.027,2.193,2.166,1.724,2.217,2.476,2.554,2.325,1.979,2.939,2.358,2.328,2.383,1.954,2.356,2.368,2.824,2.440,2.672,2.894,1.700,1.704,1.591,1.929,1.941,1.990,2.335,1.770,2.310,2.146,1.973,2.034,2.208,2.438,2.285,2.188,0.0,72.0,401,0.0
1892,2043,OAS31172_MR_d1717,2725.4,1625.3,0.0,18537.1,687.2,324.8,293.0,248.5,924.8,1463.0,410.5,1212.5,3242.7,38331.5,12479.4,3660.8,725.2,22628.9,1251.1,4175.1,3516.4,0.0,1653.0,0.0,72.2,277.9,443.8,1229.2,3702.0,38591.6,12779.7,3803.5,648.4,20712.3,1250.6,3682.3,3325.4,0.0,3195.7,0.0,77.8,3660.4,96.0,2.660,2.254,2.259,2.575,2.390,1.828,3.025,2.351,2.549,2.449,2.339,2.097,1.767,2.537,2.365,2.848,2.322,2.748,2.528,1.722,3.038,1.615,1.647,2.590,1.975,2.011,2.165,2.121,2.199,2.320,1.935,2.240,2.071,2.324,2.300,1.786,2.257,2.657,2.686,2.342,1.914,2.556,2.449,2.537,2.325,2.144,2.629,2.221,2.920,2.491,2.661,2.847,1.697,1.663,1.783,2.038,1.832,1.807,2.315,1.917,2.322,2.032,1.990,2.188,2.113,2.212,2.335,2.263,0.0,76.0,403,0.0